

networks:
  laravel:
    external: true


#volumes:
#  caddy_caddyfile:

services:
#
#
#  caddy1:
#    container_name: caddy1
#    image: caddy:2-alpine
#    ports:
#      - "80:80"
#      - "443:443"
#    volumes:
#      - ./Caddyfile:/etc/caddy/Caddyfile
#      - caddy_caddyfile:/etc/caddy
#      - '${FOLDER_SYMFONY2601}:${FOLDER_SYMFONY2601_SERV}'
#      - '${FOLDER_2602LARAVEL_TEST}:${FOLDER_2602LARAVEL_TEST_SERV}'
#    depends_on:
#      - symfony2601
#    networks:
#      - laravel

  symfony2601:
    container_name: symfony2601
    networks:
      - laravel
    expose:
      - 9000
    build:
      context: .
      dockerfile: Symfony2601.Dockerfile
    working_dir: ${FOLDER_SYMFONY2601_SERV}
    environment:
      - PHPGROUP=www-data
      - PHPUSER=www-data
      - FOLDER=${FOLDER_SYMFONY2601_SERV}
    restart: unless-stopped
    volumes:
      - '${FOLDER_SYMFONY2601}:${FOLDER_SYMFONY2601_SERV}'


  2602laravel_test2:
    container_name: 2602laravel_test2
    networks:
      - laravel
    build:
      context: .
      dockerfile: docker.2602laravel.Dockerfile
    working_dir: ${FOLDER_2602LARAVEL_TEST_SERV}
    environment:
      - PHPGROUP=www-data
      - PHPUSER=www-data
      - FOLDER=${FOLDER_2602LARAVEL_TEST_SERV}
    restart: unless-stopped
    volumes:
      - '${FOLDER_2602LARAVEL_TEST}:${FOLDER_2602LARAVEL_TEST_SERV}'
